export const eventsStore = [
    {
      title: "Day Trading Idea and Strategy",
      description: "Being an INFJ",
      date: new Date(2024, 2, 18, 15),
      image: "./image/eventspics/1.jpg",
      type: "offline",
      attendees: 1,
      category: "Business",
      distance: 5,
    },
    {
      title: "Let's Talk Networking: JPMorgan Chase in Palo Alto",
      description: "Being an INFJ",
      date: new Date(2024, 3, 19, 15),
      image: "./image/eventspics/2.jpg",
      type: "offline",
      attendees: 41,
      category: "Business",
      distance: 25,
    },
    {
      title: "Tech Talks & Quiz: Next-Gen Database Solutions for Emerging Use Cases",
      description: "Being an INFJ",
      date: new Date(2024, 2, 13, 15),
      image: "./image/eventspics/3.jpg",
      type: "online",
      attendees: 40,
      category: "Technology",
      distance: 0,
    },
    {
      title: "INFORMS San Francisco Chapter In-Person Event",
      description: "Being an INFJ",
      date: new Date(2024, 2, 28, 15),
      image: "./image/eventspics/4.jpg",
      type: "offline",
      attendees: 1,
      category: "Health and Wellbeing",
      distance: 50,
    },
    {
      title: "AI Wednesdays - Meet and Greet!",
      description: "Being an INFJ",
      date: new Date(2024, 2, 13, 15),
      image: "./image/eventspics/5.jpg",
      type: "offline",
      attendees: 29,
      category: "Technology",
      distance: 5,
    },
    {
      title: "ROS By-The-Bay March 2024",
      description: "Being an INFJ",
      date: new Date(2024, 2, 21, 15),
      image: "./image/eventspics/6.jpg",
      type: "online",
      attendees: 51,
      category: "Social Activities",
      distance: 0,
    },
    {
      title: "Free Christian Singles' Dinner",
      description: "Being an INFJ",
      date: new Date(2024, 3, 29, 15),
      image: "./image/eventspics/7.jpg",
      type: "offline",
      attendees: 11,
      category: "Hobbies and Passions",
      distance: 10,
    },
    {
      title: "In-person: Deep Dive into RAG Architectures (Food served)",
      description: "Being an INFJ",
      date: new Date(2024, 3, 14, 15),
      image: "./image/eventspics/8.jpg",
      type: "offline",
      attendees: 16,
      category: "Hobbies and Passions",
      distance: 50,
    },
  //   {
  //     title: "INFJ Personality Type - Coffee Shop Meet & Greet",
  //     description: "Being an INFJ",
  //     date: new Date(2024, 2, 23, 15),
  //     image: "https://images.unsplash.com/photo-1541167760496-1628856ab772?q=80&w=1037&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D%201037w ",
  //     type: "offline",
  //     attendees: 99,
  //     category: "Hobbies and Passions",
  //     distance: 50,
  //   },
  //   {
  //     title:
  //       "NYC AI Users - AI Tech Talks, Demo & Social: RAG Search and Customer Experience",
  //     description: "New York AI Users",
  //     date: new Date(2024, 2, 23, 11, 30),
  //     image: "https://images.unsplash.com/photo-1696258686454-60082b2c33e2?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D ",
  //     type: "offline",
  //     attendees: 43,
  //     category: "Technology",
  //     distance: 25,
  //   },
  //   {
  //     title: "Book 40+ Appointments Per Month Using AI and Automation",
  //     description: "New Jersey Business Network",
  //     date:  new Date(2024, 2, 16, 14),
  //     image: "https://images.unsplash.com/photo-1674027444485-cec3da58eef4?q=80&w=1032&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //     type: "online",
  //     category: "Technology",
  //     distance: 10,
  //   },
  //   {
  //     title: "Dump writing group weekly meetup",
  //     description: "Dump writing group",
  //     date: new Date(2024, 2, 13, 11),
  //     image: "https://plus.unsplash.com/premium_photo-1678453146992-b80d66df9152?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //     type: "online",
  //     attendees: 77,
  //     category: "Business",
  //     distance: 100,
  //   },
  //   {
  //     title: "Over 40s, 50s, & 60s Senior Singles Chat, Meet & Dating Community",
  //     description: "Over 40s, 50s, 60s Singles Chat, Meet & Dating Community",
  //     date: new Date(2024, 2, 14, 11),
  //     image: "https://plus.unsplash.com/premium_photo-1706005542509-a460d6efecb0?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //     type: "online",
  //     attendees: 140,
  //     category: "Social Activities",
  //     distance: 74,
  //   },
  //   {
  //     title: "All Nations - Manhattan Missions Church Bible Study",
  //     description: "Manhattan Bible Study Meetup Group",
  //     date: new Date(2024, 2, 14, 11),
  //     image: "https://plus.unsplash.com/premium_photo-1679488248784-65a638a3d3fc?q=80&w=870&auto=format&fit=crop&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8fA%3D%3D",
  //     type: "offline",
  //     category: "Health and Wellbeing",
  //     distance: 15,
  //   },
  ];
  